[book]
authors = ["Shawn Tabrizi"]
language = "en"
multilingual = false
src = "src"
title = "Substrate Collectables Workshop"

[output.html]
git-repository-url = "https://github.com/shawntabrizi/substrate-collectables-workshop"
git-repository-icon = "fa-github"

[preprocessor.mdinclude]
